---
title: "sandy_code"
author: "Caroline Shepherd"
date: "5/5/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=TRUE, message = FALSE, warning = FALSE}

library(tidyverse)
library(janitor)
library(rootSolve)
library(here)
library(cowplot)

carbon <- read_csv(here("HW3_data.csv")) %>% 
  select(-1) %>% 
  clean_names

low_lm <- lm(price_cents  ~ q_low_kwh, data=carbon)
high_lm <- lm(price_cents ~ q_high_kwh, data=carbon)

# need to rearrange the parameter to get Q(P)! 

# Qgg = Qlow(P) + Qlow(h) 

# Importantly, since they-intercepts are different, we know that Qagg(P) will have a kink. I include an ifelse() statement to take
# care of the kink.

# define a function to get demand

demand <- function(p, model){
  q <- (p - model$coefficients[[1]])/model$coefficients[[2]]
  q <- ifelse(q<0,0,q)
  return(q)
}

# for each p level, return estimated aggregate demand
demand_agg <- function(p){
  q <- demand(p, low_lm) + demand(p, high_lm)
  return(q)
}

price = seq(0, 30, length.out = 100)
Qagg <- map(price, demand_agg) %>% unlist()

df<- tibble(Qagg = Qagg, price = price)

ggplot(df, aes(Qagg, price)) +
  geom_line() +
  geom_text(aes(x = 2e+05, y = 5),
            label = "Aggregate Monthly Demand Curve") +
  labs(x = "Quantity in kWh",
       y = "Price")

```


```{r, fig.align = 'center', include=TRUE, message = FALSE, warning = FALSE}
# Low demand graph
low_d_reg <- ggplot(data = carbon, aes(x = q_low_kwh, y = price_cents)) +
  theme_classic() +
  geom_line() +
  geom_abline(intercept = low_lm$coefficients[1], slope = low_lm$coefficients[2], color = 'red') +
  labs(x = 'Low Income Electricity (kWh) Demand',
       y = 'Price ($)')

# High demand graph
high_d_reg <- ggplot(data = carbon, aes(x = q_high_kwh, y = price_cents)) +
  theme_classic() +
  geom_line() +
  geom_abline(intercept = high_lm$coefficients[1], slope = high_lm$coefficients[2], color = 'red') +
  labs(x = 'High Income Electricity (kWh) Demand',
       y = 'Price ($)')

plot_grid(low_d_reg, high_d_reg, ncol = 2)
```

```{r, fig.align = 'center', include=TRUE, message = FALSE, warning = FALSE}

# Storing intercepts and slopes as objects for high and low demand
low_int <- low_lm$coefficients[1] # Low Demand - intercept
low_slp <- low_lm$coefficients[2] # Low Demand - slope
high_int <- high_lm$coefficients[1] # High Demand - intercept
high_slp <- high_lm$coefficients[2] # High Demand - slope

# Creating functions for both demand groups for graphing each demand curve
d_low <- function(q) {low_slp*q + low_int}
d_high <- function(q) {high_slp*q + high_int}

# Creating an overall demand function for calculations
demand_funct <- function(p, model){ # using 'model', so either high or low demand can be used in this
  q <- (p - model$coefficients[1])/model$coefficients[2]
  q <- ifelse(q<0,0,q)
  return(q)
}

# Creating an aggregate demand function
demand_agg <- function(p){
  q <- demand_funct(p, low_lm) + demand_funct(p, high_lm)
  return(q)
}

# Creating a sequence to map the aggregate demand function for plotting
price = seq(0, 32, length.out = 100)
qagg <- map(price, demand_agg) %>% 
  unlist()

# Putting the sequence into a dataframe
df <- tibble(qagg = qagg, price = price)

# Storing the intercept and slope of the aggregate
d_agg_slp <- (0-low_int)/(demand_agg(0)-demand_agg(low_int))
d_agg_int <- 0 - d_agg_slp*demand_agg(0)
d_agg_plot <- function(q) {d_agg_slp*q + d_agg_int}

# Creating the MPC, MSC, MEC functions
mpc_slp <- (10/demand_agg(10)) # MPC slope
mpc <- function(q) {mpc_slp*q + 0} # MPC function
mpc_q <- function(p) {p/mpc_slp} # MPC in terms of Q
mec <- function(q) {1.96} # MEC funciton
msc <- function(q) {mpc(q) + mec(q)} # MSC function


# functions for calculating the consumer surplus:

CS <- function(p, model){
  q <- demand(p, model)
  cs <- 0.5*(model$coefficients[[1]] - p)*q
  return(cs)
}


# Aggregate consumer surplus function
cs_agg <- function(p){
  cs <- cs(p,low_lm) + cs(p,high_lm)
  return(cs)
}

# Producer surplus function
ps <- function(p){
  q <- mpc_q(p)
  prod_sur <- 0.5*q*p
  return(prod_sur)
}

```

### Demand Equations

# Low Income Demand:
low demand = `r low_lm$coefficients[1]` + `r low_lm$coefficients[2]` * q

# High Income Demand:
high demand = `r high_lm$coefficients[1]` + `r high_lm$coefficients[2]` * q

# Agg demand equation:
q = ((p - `r high_lm$coefficients[1]` ) / `r high_lm$coefficients[2]` ) + ((p - `r low_lm$coefficients[1]` ) / `r low_lm$coefficients[2]` )

#### this one needs to be fixed p = r agg_lm$coefficients[1]` + `r agg_lm$coefficients[2] * q


```{r, fig.align = 'center', include=TRUE, message = FALSE, warning = FALSE}
ggplot() +
  stat_function(color = "royalblue2", fun = d_low, size = 1, linetype = "twodash") +
  stat_function(color = "royalblue4", fun = d_high, size = 1, linetype = "twodash") +
  stat_function(color = "red3", fun = mpc, size = 0.75) +
  stat_function(color = "orange3", fun = msc, size = 0.75) +
  stat_function(color = "green4", fun = mec, size = 0.75) +
  geom_point(aes(mpc_q(10),10), size = 0.75, color = "blue") +
  geom_line(data = df, aes(x = qagg, y = price), color = "purple4", size = 1) +
  scale_x_continuous(name="Electricity (kWh)", limits=c(0,900000),expand = c(0, 0)) +
  scale_y_continuous(name="Price (cents)\n", limits=c(0,40),expand = c(0, 0)) +
  geom_text(aes(label = "Low Demand", x = 140000, y = 10), angle = -54, size = 3) +
  geom_text(aes(label = "High Demand", x = 370000, y = 14), angle = -33, size = 3) +
  geom_text(aes(label = "Aggregate Demand", x = 450000, y = 14.5), angle = -24, size = 3) +
  geom_text(aes(label = "MPC", x = 750000, y = 14.75), angle =11, size = 3) +
  geom_text(aes(label = "MSC", x = 800000, y = 18), angle = 11, size = 3) +
  geom_text(aes(label = "MEC", x = 850000, y = 3), size = 3) +
  theme_classic() +
  theme(legend.title = element_blank(),
        legend.position = c(0.95, 0.95), 
        legend.justification = c(1, 1),
        legend.spacing = unit(0, "cm"), 
        legend.margin = margin(0, 0, 0, 0, "cm"))
```


